/**
 * Granular navigation modifier exports without global registration side effects.
 *
 * Use `@tachui/navigation/modifiers/register` when you intentionally need
 * ModifierBuilder prototype registration side effects.
 */
export {
  navigationTitle,
  navigationBarTitleDisplayMode,
  navigationBarHidden,
  navigationBarBackButtonHidden,
  navigationBarBackButtonTitle,
  navigationBarItems,
  toolbar,
  toolbarItems,
  ToolbarItem,
  presentationDetents,
  getToolbarItemsByPlacement,
  toolbarBackground,
  toolbarBackgroundVisibility,
  toolbarForegroundColor,
  searchable,
  searchSuggestions,
  searchScopes,
  sheet,
  fullScreenCover,
  popover,
  confirmationDialog,
  inspector,
  inspectorColumnWidth,
  extractNavigationModifiers,
  getCurrentNavigationModifiers,
  hasNavigationModifiers,
  clearNavigationModifiers,
  enhanceNavigationStackWithModifiers,
  onNavigationModifierChange,
  NavigationModifierUtils,
} from './navigation-modifiers'

export type {
  SheetPresentationOptions,
  SheetEdge,
  SheetSize,
  FullScreenCoverOptions,
  PopoverArrowEdge,
  PopoverPresentationOptions,
  SearchablePlacement,
  SearchScopeOption,
  SearchScopeState,
  SearchScopesConfig,
  SearchSuggestionsInput,
  SearchableTextState,
  ConfirmationDialogAction,
  ConfirmationDialogButtonRole,
  PresentationDetent,
  ToolbarItemPlacement,
  ToolbarBackgroundVisibility,
  ToolbarBackgroundVisibilityTarget,
  ToolbarItemConfig,
  ToolbarItemInput,
  InspectorPresentationOptions,
  InspectorColumnWidthConfig,
  InspectorPresentationState,
} from './navigation-modifiers'
