// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Signatures derived from basicModifierRegistrations in packages/modifiers/src/basic/index.ts
// by packages/core/scripts/derive-modifier-signatures.ts.
// Run `bun run --filter @tachui/core derive-modifier-signatures` to regenerate.

export const basicModifierSignatures: Readonly<Record<string, string>> = {
  padding: '(optionsOrAll: ReactivePaddingOptions | PaddingValue | Signal<PaddingValue>): this',
  paddingTop: '(value: PaddingValue | Signal<PaddingValue>): this',
  paddingBottom: '(value: PaddingValue | Signal<PaddingValue>): this',
  paddingLeft: '(value: PaddingValue | Signal<PaddingValue>): this',
  paddingRight: '(value: PaddingValue | Signal<PaddingValue>): this',
  paddingLeading: '(value: PaddingValue | Signal<PaddingValue>): this',
  paddingTrailing: '(value: PaddingValue | Signal<PaddingValue>): this',
  paddingHorizontal: '(value: PaddingValue | Signal<PaddingValue>): this',
  paddingVertical: '(value: PaddingValue | Signal<PaddingValue>): this',
  margin: '(optionsOrAll: ReactiveMarginOptions | MarginValue | Signal<MarginValue>): this',
  marginTop: '(value: MarginValue | Signal<MarginValue>): this',
  marginBottom: '(value: MarginValue | Signal<MarginValue>): this',
  marginLeft: '(value: MarginValue | Signal<MarginValue>): this',
  marginRight: '(value: MarginValue | Signal<MarginValue>): this',
  marginLeading: '(value: MarginValue | Signal<MarginValue>): this',
  marginTrailing: '(value: MarginValue | Signal<MarginValue>): this',
  marginHorizontal: '(value: MarginValue | Signal<MarginValue>): this',
  marginVertical: '(value: MarginValue | Signal<MarginValue>): this',
  size: '(options: ReactiveSizeOptions): this',
  width: '(value: Dimension | Signal<Dimension>): this',
  height: '(value: Dimension | Signal<Dimension>): this',
  maxWidth: '(value: Dimension | Signal<Dimension>): this',
  maxHeight: '(value: Dimension | Signal<Dimension>): this',
  minWidth: '(value: Dimension | Signal<Dimension>): this',
  minHeight: '(value: Dimension | Signal<Dimension>): this',
  aspectRatio: '(ratio?: number, contentMode?: ContentMode): this',
  fixedSize: '(horizontal?: boolean, vertical?: boolean): this',
  frame: '(options: any): this',
  resizable: '(): this',
  layoutPriority: '(priority: number | Signal<number>): this',
  offset: '(x: number | Signal<number>, y?: number | Signal<number>): this',
  overlay: '(content: OverlayContent, alignmentOrOptions?: OverlayAlignment | Signal<OverlayAlignment> | Omit<OverlayOptions, \'content\'>): this',
  position: '(value: PositionValue | PositionCoordinates): this',
  absolutePosition: '(x: number | Signal<number>, y?: number | Signal<number>): this',
  scaleEffect: '(x: number | Signal<number>, y?: number | Signal<number>, anchor?: ScaleAnchor): this',
  zIndex: '(value: number): this',
  flexbox: '(options: ReactiveFlexboxOptions): this',
  flexGrow: '(value: number): this',
  flexShrink: '(value: number): this',
  flexBasis: '(value: FlexboxOptions[\'flexBasis\']): this',
  justifyContent: '(value: FlexboxOptions[\'justifyContent\']): this',
  alignItems: '(value: FlexboxOptions[\'alignItems\']): this',
  alignSelf: '(value: FlexboxOptions[\'alignSelf\']): this',
  gap: '(value: FlexValue): this',
  flexDirection: '(value: FlexboxOptions[\'flexDirection\']): this',
  flexWrap: '(value: FlexboxOptions[\'flexWrap\']): this',
  backgroundColor: '(color: string | any): this',
  background: '(value: string | any): this',
  backgroundImage: '(source: ImageAssetProxy | string, options?: BackgroundImageOptions): this',
  blendMode: '(mode: BlendMode): this',
  backgroundBlendMode: '(mode: BlendMode): this',
  compositingGroup: '(): this',
  border: '(optionsOrWidth: BorderOptions | number | string, color?: string, style?: BorderStyle): this',
  borderTop: '(width: number | string, color: string, style?: BorderStyle): this',
  borderBottom: '(width: number | string, color: string, style?: BorderStyle): this',
  borderLeft: '(width: number | string, color: string, style?: BorderStyle): this',
  borderRight: '(width: number | string, color: string, style?: BorderStyle): this',
  clipShape: '(shape: ClipShapeName | Shape, parameters?: Record<string, any>): this',
  clipped: '(enabled?: boolean): this',
  cornerRadius: '(value: number | Signal<number>): this',
  foregroundColor: '(color: string | any): this',
  gradientText: '(gradient: string): this',
  opacity: '(value: number | Signal<number>): this',
  fontFamily: '(family: string | AssetValue): this',
  fontSize: '(size: any): this',
  fontWeight: '(weight: any): this',
  fontStyle: '(style: FontStyle): this',
  fontPreset: '(preset: string): this',
  typography: '(options: TypographyOptions): this',
  textAlign: '(value: TextAlign): this',
  font: '(options: FontOptions | string): this',
  lineClamp: '(lines: number): this',
  wordBreak: '(value: WordBreakValue): this',
  letterSpacing: '(value: number | string): this',
  lineHeight: '(value: number | string): this',
  textDecoration: '(value: TextDecoration): this',
  textOverflow: '(value: \'clip\' | \'ellipsis\' | \'fade\' | string): this',
  textTransform: '(value: TextTransform): this',
  textCase: '(value: TextTransform): this',
  whiteSpace: '(value: \'normal\' | \'nowrap\' | \'pre\' | \'pre-wrap\' | \'pre-line\' | \'break-spaces\'): this',
  overflow: '(value: \'visible\' | \'hidden\' | \'scroll\' | \'auto\'): this',
  hyphens: '(value: HyphensValue): this',
  overflowWrap: '(value: OverflowWrapValue): this',
  allowsHitTesting: '(enabled: boolean): this',
  focusable: '(isFocusable?: boolean, interactions?: (\'activate\' | \'edit\')[]): this',
  activatable: '(): this',
  editable: '(): this',
  focused: '(focusedValue: boolean | Signal<boolean>): this',
  keyboardShortcut: '(options: KeyboardShortcutOptions): this',
  onHover: '(callback: (isHovered: boolean) => void): this',
  onMouseEnter: '(callback: (event: MouseEvent) => void): this',
  onMouseLeave: '(callback: (event: MouseEvent) => void): this',
  onMouseDown: '(callback: (event: MouseEvent) => void): this',
  onMouseUp: '(callback: (event: MouseEvent) => void): this',
  onDoubleClick: '(callback: (event: MouseEvent) => void): this',
  onContextMenu: '(callback: (event: MouseEvent) => void): this',
  onKeyDown: '(callback: (event: KeyboardEvent) => void): this',
  onKeyUp: '(callback: (event: KeyboardEvent) => void): this',
  onKeyPress: '(callback: (event: KeyboardEvent) => void): this',
  onFocus: '(callback: (isFocused: boolean) => void): this',
  onBlur: '(callback: (isFocused: boolean) => void): this',
  onContinuousHover: '(options: OnContinuousHoverOptions): this',
  onLongPressGesture: '(options: OnLongPressGestureOptions): this',
  scroll: '(config: ScrollConfig): this',
  scrollBehavior: '(value: \'auto\' | \'smooth\'): this',
  overscrollBehavior: '(value: OverscrollBehaviorValue): this',
  overscrollBehaviorX: '(value: OverscrollBehaviorValue): this',
  overscrollBehaviorY: '(value: OverscrollBehaviorValue): this',
  scrollMargin: '(margin: number | string | { top?: number | string; right?: number | string; bottom?: number | string; left?: number | string; }): this',
  scrollPadding: '(padding: number | string | { top?: number | string; right?: number | string; bottom?: number | string; left?: number | string; }): this',
  scrollSnap: '(type: \'none\' | \'x mandatory\' | \'y mandatory\' | \'x proximity\' | \'y proximity\' | \'both mandatory\' | \'both proximity\', align?: \'start\' | \'end\' | \'center\', stop?: \'normal\' | \'always\'): this',
  highPriorityGesture: '(gesture: any, including?: GestureInclusion): this',
  simultaneousGesture: '(gesture: any, including?: GestureInclusion): this',
  onTap: '(handler: (event: MouseEvent) => void): this',
  onScroll: '(handler: (event: Event) => void): this',
  onWheel: '(handler: (event: WheelEvent) => void): this',
  onInput: '(handler: (event: InputEvent) => void): this',
  onChange: '(handler: (value: any, event?: Event) => void): this',
  onCopy: '(handler: (event: ClipboardEvent) => void): this',
  onCut: '(handler: (event: ClipboardEvent) => void): this',
  onPaste: '(handler: (event: ClipboardEvent) => void): this',
  onSelect: '(handler: (event: Event) => void): this',
  onTouchStart: '(handler: (event: TouchEvent) => void): this',
  onTouchMove: '(handler: (event: TouchEvent) => void): this',
  onTouchEnd: '(handler: (event: TouchEvent) => void): this',
  onSwipeLeft: '(handler: () => void): this',
  onSwipeRight: '(handler: () => void): this',
  disabled: '(isDisabled?: boolean | Signal<boolean>): this',
  css: '(properties: ReactiveCSSOptions): this',
  cssProperty: '(property: string, value: CSSValue): this',
  cssVariable: '(name: string, value: CSSValue): this',
  utility: '(options: ReactiveUtilityOptions): this',
  cursor: '(value: UtilityOptions[\'cursor\']): this',
  display: '(value: UtilityOptions[\'display\']): this',
  overflowX: '(value: UtilityOptions[\'overflowX\']): this',
  overflowY: '(value: UtilityOptions[\'overflowY\']): this',
  outline: '(value: string): this',
  outlineOffset: '(value: number | string): this',
  asHTML: '(options?: AsHTMLOptions): this',
  navigationTitle: '(title: string): this',
  navigationBarHidden: '(hidden?: boolean): this',
  navigationBarItems: '(options: { leading?: ComponentInstance | ComponentInstance[]; trailing?: ComponentInstance | ComponentInstance[]; }): this',
  animation: '(options?: AnimationModifierProps[\'animation\']): this',
  transform: '(value: string | Signal<string>): this',
  transition: '(optionsOrProperty: TransitionConfig | string, duration?: number, easing?: string, delay?: number): this',
  rotationEffect: '(angle: number | Signal<number>, anchor?: RotationAnchor): this',
  aria: '(attributes: AriaAttributes): this',
  ariaLabel: '(value: string): this',
  ariaLive: '(value: \'off\' | \'polite\' | \'assertive\'): this',
  ariaDescribedBy: '(value: string): this',
  ariaModal: '(value: boolean): this',
  role: '(value: string): this',
  customProperties: '(options: CustomPropertiesOptions): this',
  customProperty: '(name: string, value: CSSPropertyValue, scope?: \'local\' | \'global\' | \'root\'): this',
  cssVariables: '(variables: CSSPropertiesMap): this',
  id: '(value: IdValue): this',
  elementId: '(value: IdValue): this',
  viewId: '(value: IdValue): this',
  data: '(attributes: DataAttributes): this',
  tabIndex: '(value: TabIndexValue): this',
  before: '(styles: PseudoElementStyles): this',
  after: '(styles: PseudoElementStyles): this',
  pseudoElements: '(options: PseudoElementOptions): this',
  iconBefore: '(icon: string, styles?: Omit<PseudoElementStyles, \'content\'>): this',
  iconAfter: '(icon: string, styles?: Omit<PseudoElementStyles, \'content\'>): this',
  lineBefore: '(color?: string, thickness?: number, length?: number): this',
  lineAfter: '(color?: string, thickness?: number, length?: number): this',
  quotes: '(openQuote?: string, closeQuote?: string): this',
  underline: '(color?: string, thickness?: number, opacity?: number): this',
  badge: '(color?: string, size?: number, text?: string): this',
  tooltip: '(text: string, position?: \'top\' | \'bottom\' | \'left\' | \'right\', backgroundColor?: string, textColor?: string): this',
  cornerRibbon: '(text: string, color?: string, textColor?: string): this',
  spinner: '(size?: number, color?: string, borderWidth?: number): this',
  task: '(options: NonNullable<LifecycleModifierProps[\'task\']>): this',
}

export const basicModifierCategories: Readonly<Record<string, 'layout' | 'appearance' | 'interaction' | 'animation' | 'accessibility' | 'custom'>> = {
  padding: 'layout',
  paddingTop: 'layout',
  paddingBottom: 'layout',
  paddingLeft: 'layout',
  paddingRight: 'layout',
  paddingLeading: 'layout',
  paddingTrailing: 'layout',
  paddingHorizontal: 'layout',
  paddingVertical: 'layout',
  margin: 'layout',
  marginTop: 'layout',
  marginBottom: 'layout',
  marginLeft: 'layout',
  marginRight: 'layout',
  marginLeading: 'layout',
  marginTrailing: 'layout',
  marginHorizontal: 'layout',
  marginVertical: 'layout',
  size: 'layout',
  width: 'layout',
  height: 'layout',
  maxWidth: 'layout',
  maxHeight: 'layout',
  minWidth: 'layout',
  minHeight: 'layout',
  aspectRatio: 'layout',
  fixedSize: 'layout',
  frame: 'layout',
  resizable: 'layout',
  layoutPriority: 'layout',
  offset: 'layout',
  overlay: 'layout',
  position: 'layout',
  absolutePosition: 'layout',
  scaleEffect: 'layout',
  zIndex: 'layout',
  flexbox: 'layout',
  flexGrow: 'layout',
  flexShrink: 'layout',
  flexBasis: 'layout',
  justifyContent: 'layout',
  alignItems: 'layout',
  alignSelf: 'layout',
  gap: 'layout',
  flexDirection: 'layout',
  flexWrap: 'layout',
  backgroundColor: 'appearance',
  background: 'appearance',
  backgroundImage: 'appearance',
  blendMode: 'appearance',
  backgroundBlendMode: 'appearance',
  compositingGroup: 'appearance',
  border: 'appearance',
  borderTop: 'appearance',
  borderBottom: 'appearance',
  borderLeft: 'appearance',
  borderRight: 'appearance',
  clipShape: 'appearance',
  clipped: 'appearance',
  cornerRadius: 'appearance',
  foregroundColor: 'appearance',
  gradientText: 'appearance',
  opacity: 'appearance',
  fontFamily: 'appearance',
  fontSize: 'appearance',
  fontWeight: 'appearance',
  fontStyle: 'appearance',
  fontPreset: 'appearance',
  typography: 'appearance',
  textAlign: 'appearance',
  font: 'appearance',
  lineClamp: 'appearance',
  wordBreak: 'appearance',
  letterSpacing: 'appearance',
  lineHeight: 'appearance',
  textDecoration: 'appearance',
  textOverflow: 'appearance',
  textTransform: 'appearance',
  textCase: 'appearance',
  whiteSpace: 'appearance',
  overflow: 'appearance',
  hyphens: 'appearance',
  overflowWrap: 'appearance',
  allowsHitTesting: 'interaction',
  focusable: 'interaction',
  activatable: 'interaction',
  editable: 'interaction',
  focused: 'interaction',
  keyboardShortcut: 'interaction',
  onHover: 'interaction',
  onMouseEnter: 'interaction',
  onMouseLeave: 'interaction',
  onMouseDown: 'interaction',
  onMouseUp: 'interaction',
  onDoubleClick: 'interaction',
  onContextMenu: 'interaction',
  onKeyDown: 'interaction',
  onKeyUp: 'interaction',
  onKeyPress: 'interaction',
  onFocus: 'interaction',
  onBlur: 'interaction',
  onContinuousHover: 'interaction',
  onLongPressGesture: 'interaction',
  scroll: 'interaction',
  scrollBehavior: 'interaction',
  overscrollBehavior: 'interaction',
  overscrollBehaviorX: 'interaction',
  overscrollBehaviorY: 'interaction',
  scrollMargin: 'interaction',
  scrollPadding: 'interaction',
  scrollSnap: 'interaction',
  highPriorityGesture: 'interaction',
  simultaneousGesture: 'interaction',
  onTap: 'interaction',
  onScroll: 'interaction',
  onWheel: 'interaction',
  onInput: 'interaction',
  onChange: 'interaction',
  onCopy: 'interaction',
  onCut: 'interaction',
  onPaste: 'interaction',
  onSelect: 'interaction',
  onTouchStart: 'interaction',
  onTouchMove: 'interaction',
  onTouchEnd: 'interaction',
  onSwipeLeft: 'interaction',
  onSwipeRight: 'interaction',
  disabled: 'interaction',
  css: 'custom',
  cssProperty: 'custom',
  cssVariable: 'custom',
  utility: 'custom',
  cursor: 'custom',
  display: 'custom',
  overflowX: 'custom',
  overflowY: 'custom',
  outline: 'custom',
  outlineOffset: 'custom',
  asHTML: 'custom',
  navigationTitle: 'custom',
  navigationBarHidden: 'custom',
  navigationBarItems: 'custom',
  animation: 'animation',
  transform: 'animation',
  transition: 'layout',
  rotationEffect: 'layout',
  aria: 'accessibility',
  ariaLabel: 'accessibility',
  ariaLive: 'accessibility',
  ariaDescribedBy: 'accessibility',
  ariaModal: 'accessibility',
  role: 'accessibility',
  customProperties: 'accessibility',
  customProperty: 'accessibility',
  cssVariables: 'accessibility',
  id: 'accessibility',
  elementId: 'accessibility',
  viewId: 'accessibility',
  data: 'accessibility',
  tabIndex: 'accessibility',
  before: 'custom',
  after: 'custom',
  pseudoElements: 'custom',
  iconBefore: 'custom',
  iconAfter: 'custom',
  lineBefore: 'custom',
  lineAfter: 'custom',
  quotes: 'custom',
  underline: 'custom',
  badge: 'custom',
  tooltip: 'custom',
  cornerRibbon: 'custom',
  spinner: 'custom',
  task: 'custom',
}
