/**
 * @tachui/modifiers/effects - Visual effects and advanced modifiers
 *
 * This package provides comprehensive visual effects including filters,
 * transforms, backdrop effects, shadows, and interactive hover effects.
 *
 * Segmented preload: Synchronously imports and registers all effects.
 */

// Registry registration for effects
import { globalModifierRegistry } from '@tachui/registry'

// Import specific factory functions to register them
import {
  blur,
  brightness,
  contrast,
  filter,
  saturate,
  grayscale,
  sepia,
  hueRotate,
  invert,
  filterDropShadow,
  vintagePhoto,
  blackAndWhite,
  vibrant,
  warmTone,
  coolTone,
  faded,
  highKey,
  lowKey,
  softFocus,
  highContrastMode,
  subtleBlur,
  darkModeInvert,
  colorInvert,
  saturation,
  hueRotation,
} from './filters'
import {
  transform,
  rotate,
  scale,
  translate,
  skew,
  rotateX,
  rotateY,
  rotateZ,
  perspective,
  advancedTransform,
  matrix,
  matrix3d,
  rotate3d,
  scale3d,
  translate3d,
  scaleX,
  scaleY,
  scaleZ,
  translateX,
  translateY,
  translateZ,
  perspectiveOrigin,
  transformStyle,
  backfaceVisibility,
} from './transforms'
import {
  shadow,
  textShadow,
  dropShadow,
  insetShadow,
  elevationShadow,
  glowEffect,
  neonEffect,
  neumorphism,
  neumorphismPressed,
  layeredShadow,
  textShadowSubtle,
  textShadowStrong,
  textOutline,
  textEmbossed,
  textEngraved,
  swiftUIShadow,
  reactiveShadow,
  animatedShadow,
} from './shadows'
import {
  hover,
  active,
  focus,
  pressed,
  hoverEffect,
  hoverWithTransition,
  conditionalHover,
  interactiveCursor,
  draggableCursor,
  textCursor,
  disabledCursor,
  loadingCursor,
  helpCursor,
  zoomCursor,
  buttonHover,
  cardHover,
  linkHover,
  imageHover,
} from './effects'
import { backdropFilter, glassmorphism, customGlassmorphism } from './backdrop'

// Register all effects factories synchronously
const effectRegistrations: Array<[string, (...args: any[]) => any]> = [
  // Filter system
  ['blur', blur],
  ['brightness', brightness],
  ['contrast', contrast],
  ['filter', filter],
  ['saturate', saturate],
  ['grayscale', grayscale],
  ['sepia', sepia],
  ['hueRotate', hueRotate],
  ['invert', invert],
  ['filterDropShadow', filterDropShadow],
  ['vintagePhoto', vintagePhoto],
  ['blackAndWhite', blackAndWhite],
  ['vibrant', vibrant],
  ['warmTone', warmTone],
  ['coolTone', coolTone],
  ['faded', faded],
  ['highKey', highKey],
  ['lowKey', lowKey],
  ['softFocus', softFocus],
  ['highContrastMode', highContrastMode],
  ['subtleBlur', subtleBlur],
  ['darkModeInvert', darkModeInvert],
  ['colorInvert', colorInvert],
  ['saturation', saturation],
  ['hueRotation', hueRotation],

  // Transform utilities
  ['transform', transform],
  ['scale', scale],
  ['rotate', rotate],
  ['translate', translate],
  ['skew', skew],
  ['rotateX', rotateX],
  ['rotateY', rotateY],
  ['rotateZ', rotateZ],
  ['perspective', perspective],
  ['advancedTransform', advancedTransform],
  ['matrix', matrix],
  ['matrix3d', matrix3d],
  ['rotate3d', rotate3d],
  ['scale3d', scale3d],
  ['translate3d', translate3d],
  ['scaleX', scaleX],
  ['scaleY', scaleY],
  ['scaleZ', scaleZ],
  ['translateX', translateX],
  ['translateY', translateY],
  ['translateZ', translateZ],
  ['perspectiveOrigin', perspectiveOrigin],
  ['transformStyle', transformStyle],
  ['backfaceVisibility', backfaceVisibility],

  // Shadows
  ['shadow', shadow],
  ['textShadow', textShadow],
  ['dropShadow', dropShadow],
  ['insetShadow', insetShadow],
  ['elevationShadow', elevationShadow],
  ['glowEffect', glowEffect],
  ['neonEffect', neonEffect],
  ['neumorphism', neumorphism],
  ['neumorphismPressed', neumorphismPressed],
  ['layeredShadow', layeredShadow],
  ['textShadowSubtle', textShadowSubtle],
  ['textShadowStrong', textShadowStrong],
  ['textOutline', textOutline],
  ['textEmbossed', textEmbossed],
  ['textEngraved', textEngraved],
  ['swiftUIShadow', swiftUIShadow],
  ['reactiveShadow', reactiveShadow],
  ['animatedShadow', animatedShadow],

  // Interactive effects
  ['hover', hover],
  ['active', active],
  ['focus', focus],
  ['pressed', pressed],
  ['hoverEffect', hoverEffect],
  ['hoverWithTransition', hoverWithTransition],
  ['conditionalHover', conditionalHover],
  ['interactiveCursor', interactiveCursor],
  ['draggableCursor', draggableCursor],
  ['textCursor', textCursor],
  ['disabledCursor', disabledCursor],
  ['loadingCursor', loadingCursor],
  ['helpCursor', helpCursor],
  ['zoomCursor', zoomCursor],
  ['buttonHover', buttonHover],
  ['cardHover', cardHover],
  ['linkHover', linkHover],
  ['imageHover', imageHover],

  // Backdrop / glassmorphism
  ['backdropFilter', backdropFilter],
  ['glassmorphism', glassmorphism],
  ['customGlassmorphism', customGlassmorphism],
]

effectRegistrations.forEach(([name, factory]) => {
  if (!globalModifierRegistry.has(name)) {
    globalModifierRegistry.register(name, factory as any)
  }
})

// Export all types and utilities

// Re-export all effects with explicit aliases to resolve conflicts
export {
  blur,
  brightness,
  contrast,
  filter,
  saturate,
  grayscale,
  sepia,
  hueRotate,
  invert,
  filterDropShadow,
  vintagePhoto,
  blackAndWhite,
  vibrant,
  warmTone,
  coolTone,
  faded,
  highKey,
  lowKey,
  softFocus,
  highContrastMode,
  subtleBlur,
  darkModeInvert,
  colorInvert,
  saturation,
  hueRotation,
} from './filters'
export {
  transform,
  rotate,
  scale,
  translate,
  skew,
  rotateX,
  rotateY,
  rotateZ,
  perspective,
  advancedTransform,
  matrix,
  matrix3d,
  rotate3d,
  scale3d,
  translate3d,
  scaleX,
  scaleY,
  scaleZ,
  translateX,
  translateY,
  translateZ,
  perspectiveOrigin,
  transformStyle,
  backfaceVisibility,
} from './transforms'
export {
  shadow,
  textShadow,
  dropShadow,
  insetShadow,
  elevationShadow,
  glowEffect,
  neonEffect,
  neumorphism,
  neumorphismPressed,
  layeredShadow,
  textShadowSubtle,
  textShadowStrong,
  textOutline,
  textEmbossed,
  textEngraved,
  swiftUIShadow,
  reactiveShadow,
  animatedShadow,
} from './shadows'
export {
  hover,
  active,
  focus,
  pressed,
  hoverEffect,
  hoverWithTransition,
  conditionalHover,
  interactiveCursor,
  draggableCursor,
  textCursor,
  disabledCursor,
  loadingCursor,
  helpCursor,
  zoomCursor,
  buttonHover,
  cardHover,
  linkHover,
  imageHover,
} from './effects'
export { backdropFilter, glassmorphism, customGlassmorphism } from './backdrop'

// Legacy exports for backward compatibility - removed conflicting exports
// Note: filterDropShadow and ReactiveTextShadowConfig conflicts resolved by importing from specific modules

// Only log in development to avoid production noise
if (process.env.NODE_ENV === 'development') {
  console.log(`@tachui/modifiers/effects: Preloaded and registered ${effectRegistrations.length} effects modifiers.`)
}
