// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Signatures derived from effectRegistrations in packages/modifiers/src/effects/index.ts
// by packages/core/scripts/derive-modifier-signatures.ts.
// Run `bun run --filter @tachui/core generate-modifier-types` to regenerate.

export const effectModifierSignatures: Readonly<Record<string, string>> = {
  blur: '(radius: number): this',
  brightness: '(value: number): this',
  contrast: '(value: number): this',
  filter: '(config: FilterConfig | string): this',
  saturate: '(value: number): this',
  grayscale: '(value: number | boolean): this',
  sepia: '(value: number | boolean): this',
  hueRotate: '(angle: string | number): this',
  invert: '(value: number | boolean): this',
  filterDropShadow: '(shadow: string): this',
  vintagePhoto: '(sepiaAmount?: number, contrastAmount?: number): this',
  blackAndWhite: '(contrastAmount?: number): this',
  vibrant: '(saturationAmount?: number, contrastAmount?: number): this',
  warmTone: '(hueShift?: string): this',
  coolTone: '(hueShift?: string): this',
  faded: '(contrastAmount?: number, saturationAmount?: number): this',
  highKey: '(brightnessAmount?: number, contrastAmount?: number): this',
  lowKey: '(brightnessAmount?: number, contrastAmount?: number): this',
  softFocus: '(blurAmount?: number): this',
  highContrastMode: '(): this',
  subtleBlur: '(): this',
  darkModeInvert: '(): this',
  colorInvert: '(): this',
  saturation: '(amount: number): this',
  hueRotation: '(angle: string): this',
  transform: '(value: TransformConfig | Transform3DConfig | string | Signal<string>): this',
  scale: '(value: ReactiveTransformValue<number> | { x?: ReactiveTransformValue<number>; y?: ReactiveTransformValue<number>; }): this',
  rotate: '(angle: ReactiveTransformValue<string | number>): this',
  translate: '(offset: { x?: ReactiveTransformValue<number | string>; y?: ReactiveTransformValue<number | string>; }): this',
  skew: '(angles: { x?: ReactiveTransformValue<string | number>; y?: ReactiveTransformValue<string | number>; }): this',
  rotateX: '(angle: ReactiveTransformValue<string | number>): this',
  rotateY: '(angle: ReactiveTransformValue<string | number>): this',
  rotateZ: '(angle: ReactiveTransformValue<string | number>): this',
  perspective: '(value: ReactiveTransformValue<number>): this',
  advancedTransform: '(config: Advanced3DTransformConfig | MatrixTransformConfig): this',
  matrix: '(values: [ number, number, number, number, number, number ]): this',
  matrix3d: '(values: [ number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number ]): this',
  rotate3d: '(x: number, y: number, z: number, angle: string): this',
  scale3d: '(x: number, y: number, z: number): this',
  translate3d: '(x?: number | string, y?: number | string, z?: number | string): this',
  scaleX: '(value: number): this',
  scaleY: '(value: number): this',
  scaleZ: '(value: number): this',
  translateX: '(value: number | string): this',
  translateY: '(value: number | string): this',
  translateZ: '(value: number | string): this',
  perspectiveOrigin: '(value: string): this',
  transformStyle: '(value: \'flat\' | \'preserve-3d\'): this',
  backfaceVisibility: '(value: \'visible\' | \'hidden\'): this',
  shadows: '(configs: ShadowConfig[]): this',
  shadowPreset: '(preset: ShadowPreset): this',
  shadow: '(config: ShadowConfig | ShadowConfig[] | string): this',
  textShadow: '(config: ReactiveTextShadowConfig | ReactiveTextShadowConfig[] | string): this',
  dropShadow: '(config: DropShadowConfig | DropShadowConfig[] | string): this',
  insetShadow: '(config: Omit<ShadowConfig, \'inset\'>): this',
  elevationShadow: '(level: number): this',
  glowEffect: '(color: string, intensity?: number): this',
  neonEffect: '(color: string, intensity?: number): this',
  neumorphism: '(_backgroundColor: string, dark?: boolean): this',
  neumorphismPressed: '(_backgroundColor: string, dark?: boolean): this',
  layeredShadow: '(layers?: number, opacityMultiplier?: number): this',
  textShadowSubtle: '(color?: string): this',
  textShadowStrong: '(color?: string): this',
  textOutline: '(color: string, thickness?: number): this',
  textEmbossed: '(lightColor?: string, darkColor?: string): this',
  textEngraved: '(darkColor?: string, lightColor?: string): this',
  swiftUIShadow: '(config?: { color?: string; radius?: number; x?: number; y?: number; }): this',
  reactiveShadow: '(condition: Signal<boolean>, trueShadow: ShadowConfig, falseShadow?: ShadowConfig): this',
  animatedShadow: '(_duration?: number): this',
  hover: '(styles: HoverStyles, transition?: string | number): this',
  active: '(styles: HoverStyles): this',
  focus: '(styles: HoverStyles): this',
  pressed: '(styles: HoverStyles): this',
  hoverEffect: '(effect: SwiftUIHoverEffect, isEnabled?: boolean | Signal<boolean>): this',
  hoverWithTransition: '(styles: HoverStyles, duration?: number): this',
  conditionalHover: '(effect: SwiftUIHoverEffect, isEnabled: boolean | Signal<boolean>): this',
  interactiveCursor: '(): this',
  draggableCursor: '(): this',
  textCursor: '(): this',
  disabledCursor: '(): this',
  loadingCursor: '(): this',
  helpCursor: '(): this',
  zoomCursor: '(mode?: \'in\' | \'out\'): this',
  buttonHover: '(): this',
  cardHover: '(): this',
  linkHover: '(): this',
  imageHover: '(): this',
  backdropFilter: '(value: BackdropFilterConfig | string, fallbackColor?: ColorValue): this',
  glassmorphism: '(intensity?: GlassmorphismIntensity, customFallback?: ColorValue): this',
  customGlassmorphism: '(blur: number, saturate?: number, brightness?: number, fallbackColor?: ColorValue): this',
}

export const effectModifierCategories: Readonly<Record<string, 'layout' | 'appearance' | 'interaction' | 'animation' | 'accessibility' | 'custom'>> = {
  blur: 'appearance',
  brightness: 'appearance',
  contrast: 'appearance',
  filter: 'appearance',
  saturate: 'appearance',
  grayscale: 'appearance',
  sepia: 'appearance',
  hueRotate: 'appearance',
  invert: 'appearance',
  filterDropShadow: 'appearance',
  vintagePhoto: 'appearance',
  blackAndWhite: 'appearance',
  vibrant: 'appearance',
  warmTone: 'appearance',
  coolTone: 'appearance',
  faded: 'appearance',
  highKey: 'appearance',
  lowKey: 'appearance',
  softFocus: 'appearance',
  highContrastMode: 'appearance',
  subtleBlur: 'appearance',
  darkModeInvert: 'appearance',
  colorInvert: 'appearance',
  saturation: 'appearance',
  hueRotation: 'appearance',
  transform: 'appearance',
  scale: 'appearance',
  rotate: 'appearance',
  translate: 'appearance',
  skew: 'appearance',
  rotateX: 'appearance',
  rotateY: 'appearance',
  rotateZ: 'appearance',
  perspective: 'appearance',
  advancedTransform: 'appearance',
  matrix: 'appearance',
  matrix3d: 'appearance',
  rotate3d: 'appearance',
  scale3d: 'appearance',
  translate3d: 'appearance',
  scaleX: 'appearance',
  scaleY: 'appearance',
  scaleZ: 'appearance',
  translateX: 'appearance',
  translateY: 'appearance',
  translateZ: 'appearance',
  perspectiveOrigin: 'appearance',
  transformStyle: 'appearance',
  backfaceVisibility: 'appearance',
  shadows: 'appearance',
  shadowPreset: 'appearance',
  shadow: 'appearance',
  textShadow: 'appearance',
  dropShadow: 'appearance',
  insetShadow: 'appearance',
  elevationShadow: 'appearance',
  glowEffect: 'appearance',
  neonEffect: 'appearance',
  neumorphism: 'appearance',
  neumorphismPressed: 'appearance',
  layeredShadow: 'appearance',
  textShadowSubtle: 'appearance',
  textShadowStrong: 'appearance',
  textOutline: 'appearance',
  textEmbossed: 'appearance',
  textEngraved: 'appearance',
  swiftUIShadow: 'appearance',
  reactiveShadow: 'appearance',
  animatedShadow: 'appearance',
  hover: 'appearance',
  active: 'appearance',
  focus: 'appearance',
  pressed: 'appearance',
  hoverEffect: 'appearance',
  hoverWithTransition: 'appearance',
  conditionalHover: 'appearance',
  interactiveCursor: 'appearance',
  draggableCursor: 'appearance',
  textCursor: 'appearance',
  disabledCursor: 'appearance',
  loadingCursor: 'appearance',
  helpCursor: 'appearance',
  zoomCursor: 'appearance',
  buttonHover: 'appearance',
  cardHover: 'appearance',
  linkHover: 'appearance',
  imageHover: 'appearance',
  backdropFilter: 'appearance',
  glassmorphism: 'appearance',
  customGlassmorphism: 'appearance',
}
