// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Signatures derived from filterRegistrations in packages/modifiers/src/preload/filters.ts
// by packages/core/scripts/derive-modifier-signatures.ts.
// Run `bun run --filter @tachui/core generate-modifier-types` to regenerate.

export const filterModifierSignatures: Readonly<Record<string, string>> = {
  blur: '(radius: number): this',
  brightness: '(value: number): this',
  contrast: '(value: number): this',
  filter: '(config: FilterConfig | string): this',
  saturate: '(value: number): this',
  grayscale: '(value: number | boolean): this',
  sepia: '(value: number | boolean): this',
  hueRotate: '(angle: string | number): this',
  invert: '(value: number | boolean): this',
  filterDropShadow: '(shadow: string): this',
  vintagePhoto: '(sepiaAmount?: number, contrastAmount?: number): this',
  blackAndWhite: '(contrastAmount?: number): this',
  vibrant: '(saturationAmount?: number, contrastAmount?: number): this',
  warmTone: '(hueShift?: string): this',
  coolTone: '(hueShift?: string): this',
  faded: '(contrastAmount?: number, saturationAmount?: number): this',
  highKey: '(brightnessAmount?: number, contrastAmount?: number): this',
  lowKey: '(brightnessAmount?: number, contrastAmount?: number): this',
  softFocus: '(blurAmount?: number): this',
  highContrastMode: '(): this',
  subtleBlur: '(): this',
  darkModeInvert: '(): this',
  colorInvert: '(): this',
  saturation: '(amount: number): this',
  hueRotation: '(angle: string): this',
}

export const filterModifierCategories: Readonly<Record<string, 'layout' | 'appearance' | 'interaction' | 'animation' | 'accessibility' | 'custom'>> = {
  blur: 'appearance',
  brightness: 'appearance',
  contrast: 'appearance',
  filter: 'appearance',
  saturate: 'appearance',
  grayscale: 'appearance',
  sepia: 'appearance',
  hueRotate: 'appearance',
  invert: 'appearance',
  filterDropShadow: 'appearance',
  vintagePhoto: 'appearance',
  blackAndWhite: 'appearance',
  vibrant: 'appearance',
  warmTone: 'appearance',
  coolTone: 'appearance',
  faded: 'appearance',
  highKey: 'appearance',
  lowKey: 'appearance',
  softFocus: 'appearance',
  highContrastMode: 'appearance',
  subtleBlur: 'appearance',
  darkModeInvert: 'appearance',
  colorInvert: 'appearance',
  saturation: 'appearance',
  hueRotation: 'appearance',
}
