name: Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '10.14.0'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run tests
        run: pnpm test:ci
      
      - name: Build packages
        run: pnpm build
      
      - name: Generate API docs
        run: pnpm docs:api
      
      - name: Extract version from tag
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Update package versions
        run: |
          pnpm version ${{ steps.version.outputs.version }} --no-git-tag-version
          cd packages/core && pnpm version ${{ steps.version.outputs.version }} --no-git-tag-version
          cd ../forms && pnpm version ${{ steps.version.outputs.version }} --no-git-tag-version
          cd ../navigation && pnpm version ${{ steps.version.outputs.version }} --no-git-tag-version
          cd ../symbols && pnpm version ${{ steps.version.outputs.version }} --no-git-tag-version
          cd ../mobile-patterns && pnpm version ${{ steps.version.outputs.version }} --no-git-tag-version
          cd ../cli && pnpm version ${{ steps.version.outputs.version }} --no-git-tag-version
      
      - name: Publish to npm
        run: pnpm -r publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: tachUI ${{ steps.version.outputs.version }}
          body: |
            ## tachUI ${{ steps.version.outputs.version }}
            
            This release includes updates across the tachUI framework packages.
            
            ### Installation
            ```bash
            npm install @tachui/core@${{ steps.version.outputs.version }}
            ```
            
            ### Documentation
            - [Getting Started](https://github.com/tach-UI/tachUI/blob/main/docs/guide/getting-started.md)
            - [API Reference](https://github.com/tach-UI/tachUI/tree/main/docs/api)
            - [Examples](https://github.com/tach-UI/tachUI/tree/main/apps/examples)
          draft: false
          prerelease: ${{ contains(steps.version.outputs.version, '-') }}
          generate_release_notes: true